# Some R gotchas

### Dropped dimensions

For matrix:

```{r}
m <- matrix(1:6, ncol=3)
m
m[1,] # vector
m[,1] # vector
m[1,,drop=FALSE] # matrix
```

For data.frame:

```{r}
df <- data.frame(a=1:3,b=4:6)
df
df[1,] # data.frame
df[,1] # vector
df[,1,drop=FALSE] # data.frame
```

### stringsAsFactors: data.frame() and read.table()

```{r}
df <- data.frame(a=c("10","11","12"))
as.numeric(df$a) + 1
df <- data.frame(a=c("10","11","12"), stringsAsFactors=FALSE)
as.numeric(df$a) + 1
```

### Logical operators

```{r}
c(TRUE,TRUE,FALSE) & c(FALSE,TRUE,TRUE) # element-wise
c(TRUE,TRUE,FALSE) && c(FALSE,TRUE,TRUE) # just the first
x <- "hi"
is.numeric(x) && x + 1 # evaluates left to right
is.numeric(x) & x + 1 # produces error
```

### sapply() and apply() return columns

```{r}
m <- matrix(1:6, ncol=3)
m^2
apply(m, 2, `^`, 2) # column-wise, ok
apply(m, 1, `^`, 2) # gives back row-wise operation as columns
```

### Column names restricted characters

```{r}
df <- data.frame("test-it-#1"=1:2)
df
make.names("test-it-#1") # this function is used
```

### Removing columns by name

```{r}
df <- data.frame(a=1:2,b=3:4,c=5:6,d=7:8)
df[,-(2:3)] # numeric index ok 
df[,-c("b","c")] # not character index
subset(df, select=-c(b,c)) # by name works here
```

